### ISSUE TITLE
Cannot compile or use any of your examples

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [9214/7guis-red#1]
For example my CRUD.red compilation process has returned me:
*** Script Error: deep-reactor has no value
*** Where: do
*** Stack: do-file  

I am using Red 0.64 on my Linux (ubuntu).

Best,

Michal

**Comment by 9214** [comment]
@the-man-with-a-golden-mind hi Michał, please use the [latest](https://static.red-lang.org/dl/auto/linux/red-latest) Red release (rather than the stable one). Note that you need to install 32-bit version of GTK3 library to try out the examples. See [here](https://github.com/red/red/wiki/%5BNOTE%5D-Linux-GTK-dependencies) for a full list of dependencies.

FYI, the compilation is not mandatory, since scripts can be interpreted directly from the REPL. But if you want to compile anyways, be sure to use `-r` flag (and `-e` in case the compiled binary does not work as expected for some reason). For example:

```shell
red -r -e ./tasks/CRUD.red
```

Also, [`review`](https://github.com/9214/7guis-red/tree/review) branch contains a couple of bug fixes.

Cheers.

**Comment by 9214** [comment]
I've double-checked all the tasks with https://github.com/red/red/commit/32f10e8a3cb058fd3274bc024f65a809124dd699build on Linux Mint box: all of them run as expected and compile just fine.
